# Generated by Django 5.0.3 on 2024-03-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_tasklist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
